[package]
name = "LLM-Projects"
version = "0.1.0"
edition = "2024"

[dependencies]
kalosm = {version = "0.3.2", features = ["language", "sound", "vision"]}
tokio = {version = "1.40.0", features = ["full"]}
futures-util = "0.3.30"
image = "0.24.9"
