version: "3.8"

services:
  tcp_rust_server:
    build: .
    container_name: tcp_rust_server
    working_dir: /app
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: ./run_server.sh
    networks:
      mynet:
        ipv4_address: 192.168.0.2

  tcp_rust_client:
    build: .
    container_name: tcp_rust_client
    working_dir: /app
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: ./run_client.sh
    networks:
      mynet:
        ipv4_address: 192.168.0.3

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
