version: "3.8"

services:
  tcp_rust:
    build: .
    container_name: tcp_rust_server
    working_dir: /app
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

  tcp_rust_client:
    build: .
    container_name: tcp_rust_client
    working_dir: /app
    volumes:
      - .:/app
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
