[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"

[[bench]]
name = "ntt"
harness = false

[profile.release]
opt-level = 3
lto = true
target-cpu = "skylake"
target-feature = "+avx2"
