[package]
name = "LLMQdrantVectorDB"
version = "0.1.0"
edition = "2024"

[dependencies]
qdrant-client = "1.14.0"
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
