[package]
name = "MPC-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.1.5", features = ["transport-io"] }
tokio = { version = "1.43.0", features = ["full"] }
serde_json = "1.0.139"
serde = {version = "1.0.218", features = ["derive"]}
