[package]
name = "AI-Agent-Hugging-Face"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-core = "0.12.0"
tokio = {version = "1.43.0", features = ["full"]}
serde = {version = "1.0.219", features = ["derive"]}
thiserror = "1.0.69"
serde_json = "1.0.139"
dotenv = "0.15.0"
